# Generated by Django 4.2.27 on 2025-12-03 22:47

import apps.prompts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_uploadedimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.prompts.models.user_image_upload_to),
        ),
    ]
